### ISSUE TITLE
how to set adv trigger using chA and chB with 3206D 

### ISSUE THREAD

**Issue by lucylii** [picotech/picosdk-ps3000a-matlab-instrument-driver#1]
I need to set a advanced trigger with two channels,channel A is below to -1000mv and channel B below 1000mv.  Since  don't have the advanced trigger example for ps3000,I tried the ps5000 advtrigger example using the code as below
_**% Set Advanced trigger
status.advTrigStatus = invoke(ps3000aDeviceObj, 'setAdvancedTrigger', _channelProperties,_ triggerConditions, triggerDirections, triggerDelay, autoTrigMs);**_
and  I get the error is :
**Error using icdevice/invoke (line 54)
The function setAdvancedTrigger is not supported by this device object.
This method is supported by the trigger channel object.**
 
Does the 3206D have the setAdvancedTrigger function,and how to set two channels with ADD function ?

**Comment by hsmistry** [comment]
@lucylii, please see this [forum post](https://www.picotech.com/support/topic32171.html#p112281) for guidance on the `setAdnacedTrigger()` function.

**Comment by hsmistry** [comment]
Hi lucylii,

Looking at the code, it appears that you have based the example on the code from the PicoScope 4000 Series (A API) Instrument Driver which uses a different model for setting up advanced triggers.

If you open the picotech_ps3000a_generic.mdd file in the MATLAB Instrument Driver editor, you can find the `setAdvancedTrigger()` function in the Trigger group. There are three parameters that you need to pass which are all structures.

I would suggest referring to the [advanced trigger example](https://github.com/picotech/picosdk-ps5000a-matlab-instrument-driver/blob/master/examples/PS5000A_ID_Block_Adv_Trig_Example.m) for the PicoScope 5000 Series which follows a similar process but has a couple of extra parameters which are properties of the Trigger group for the Instrument Driver you are using.

If you have further questions, please contact us via the forum link above or via our [Support e-mail](https://www.picotech.com/tech-support).
